/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flexbox;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

public class GUI extends javax.swing.JFrame
{

    /**
     * Creates new form GUI
     */
    public GUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        gradeButtonGroup = new javax.swing.ButtonGroup();
        colourButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        inputPanel = new javax.swing.JPanel();
        sizePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        widthInput = new javax.swing.JSpinner();
        heightInput = new javax.swing.JSpinner();
        depthInput = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        quantityInput = new javax.swing.JSpinner();
        gradePanel = new javax.swing.JPanel();
        grade1RadioButton = new javax.swing.JRadioButton();
        grade2RadioButton = new javax.swing.JRadioButton();
        grade3RadioButton = new javax.swing.JRadioButton();
        grade4RadioButton = new javax.swing.JRadioButton();
        grade5RadioButton = new javax.swing.JRadioButton();
        colourPanel = new javax.swing.JPanel();
        colourNoneRadioButton = new javax.swing.JRadioButton();
        colour1RadioButton = new javax.swing.JRadioButton();
        colour2RadioButton = new javax.swing.JRadioButton();
        otherPanel = new javax.swing.JPanel();
        reinforcedBottomInput = new javax.swing.JToggleButton();
        reinforcedCornerInput = new javax.swing.JToggleButton();
        sealableTopInput = new javax.swing.JToggleButton();
        controlsPanel = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();
        addToOrderButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        price = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FlexBox Order");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        output.setColumns(20);
        output.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        output.setLineWrap(true);
        output.setRows(5);
        output.setWrapStyleWord(true);
        jScrollPane1.setViewportView(output);

        inputPanel.setLayout(new java.awt.GridBagLayout());

        sizePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Size (in metres, 0.1 - 5)"));
        sizePanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Width  Height  Depth");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        sizePanel.add(jLabel1, gridBagConstraints);

        widthInput.setModel(new javax.swing.SpinnerNumberModel(0.1d, 0.1d, 5.0d, 0.01d));
        widthInput.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                widthInputStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        sizePanel.add(widthInput, gridBagConstraints);

        heightInput.setModel(new javax.swing.SpinnerNumberModel(0.1d, 0.1d, 5.0d, 0.01d));
        heightInput.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                heightInputStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        sizePanel.add(heightInput, gridBagConstraints);

        depthInput.setModel(new javax.swing.SpinnerNumberModel(0.1d, 0.1d, 5.0d, 0.01d));
        depthInput.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                depthInputStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        sizePanel.add(depthInput, gridBagConstraints);

        jLabel2.setText("Quantity Max: 100");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        sizePanel.add(jLabel2, gridBagConstraints);

        quantityInput.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        quantityInput.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                quantityInputStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        sizePanel.add(quantityInput, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        inputPanel.add(sizePanel, gridBagConstraints);

        gradePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Grade"));
        gradePanel.setToolTipText("");
        gradePanel.setName(""); // NOI18N
        gradePanel.setLayout(new java.awt.GridLayout(1, 0));

        gradeButtonGroup.add(grade1RadioButton);
        grade1RadioButton.setSelected(true);
        grade1RadioButton.setText("1");
        grade1RadioButton.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                grade1RadioButtonStateChanged(evt);
            }
        });
        gradePanel.add(grade1RadioButton);

        gradeButtonGroup.add(grade2RadioButton);
        grade2RadioButton.setText("2");
        grade2RadioButton.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                grade2RadioButtonStateChanged(evt);
            }
        });
        gradePanel.add(grade2RadioButton);

        gradeButtonGroup.add(grade3RadioButton);
        grade3RadioButton.setText("3");
        grade3RadioButton.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                grade3RadioButtonStateChanged(evt);
            }
        });
        gradePanel.add(grade3RadioButton);

        gradeButtonGroup.add(grade4RadioButton);
        grade4RadioButton.setText("4");
        grade4RadioButton.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                grade4RadioButtonStateChanged(evt);
            }
        });
        gradePanel.add(grade4RadioButton);

        gradeButtonGroup.add(grade5RadioButton);
        grade5RadioButton.setText("5");
        grade5RadioButton.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                grade5RadioButtonStateChanged(evt);
            }
        });
        gradePanel.add(grade5RadioButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        inputPanel.add(gradePanel, gridBagConstraints);

        colourPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Colour"));
        colourPanel.setLayout(new java.awt.GridLayout(1, 0));

        colourButtonGroup.add(colourNoneRadioButton);
        colourNoneRadioButton.setSelected(true);
        colourNoneRadioButton.setText("None");
        colourNoneRadioButton.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                colourNoneRadioButtonStateChanged(evt);
            }
        });
        colourPanel.add(colourNoneRadioButton);

        colourButtonGroup.add(colour1RadioButton);
        colour1RadioButton.setText("1");
        colour1RadioButton.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                colour1RadioButtonStateChanged(evt);
            }
        });
        colourPanel.add(colour1RadioButton);

        colourButtonGroup.add(colour2RadioButton);
        colour2RadioButton.setText("2");
        colour2RadioButton.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                colour2RadioButtonStateChanged(evt);
            }
        });
        colourPanel.add(colour2RadioButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        inputPanel.add(colourPanel, gridBagConstraints);

        otherPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Other"));
        otherPanel.setLayout(new java.awt.GridLayout(3, 0));

        reinforcedBottomInput.setText("Reinforced Bottom");
        reinforcedBottomInput.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                reinforcedBottomInputStateChanged(evt);
            }
        });
        otherPanel.add(reinforcedBottomInput);

        reinforcedCornerInput.setText("Reinforced Corners");
        reinforcedCornerInput.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                reinforcedCornerInputStateChanged(evt);
            }
        });
        otherPanel.add(reinforcedCornerInput);

        sealableTopInput.setText("Sealable Top");
        sealableTopInput.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                sealableTopInputStateChanged(evt);
            }
        });
        otherPanel.add(sealableTopInput);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        inputPanel.add(otherPanel, gridBagConstraints);

        controlsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls"));
        controlsPanel.setLayout(new java.awt.GridLayout(2, 0));

        clearButton.setText("Clear Order");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                clearButtonMouseClicked(evt);
            }
        });
        controlsPanel.add(clearButton);

        addToOrderButton.setText("Add To Order");
        addToOrderButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                addToOrderButtonMouseClicked(evt);
            }
        });
        controlsPanel.add(addToOrderButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        inputPanel.add(controlsPanel, gridBagConstraints);

        errorLabel.setText(" ");
        errorLabel.setOpaque(true);

        price.setText("Total Price: £0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(price)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorLabel)
                    .addComponent(price))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToOrderButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_addToOrderButtonMouseClicked
    {//GEN-HEADEREND:event_addToOrderButtonMouseClicked
        // TODO add your handling code here:
        if (order.canSupply(depth, width, depth, grade, colour, sealableTop, reinforcedBottom, reinforcedCorner, quantity))
        {
            Box b = order.addBox(height, width, depth, grade, colour, sealableTop, reinforcedBottom, reinforcedCorner, quantity);
            text += b.printBox();
            output.setText(text);
            DecimalFormat df = new DecimalFormat("0.00");
            price.setText("Total Price: £" + df.format(order.totalPrice()).replaceAll("\\.00$", ""));
        } else
        {
            JOptionPane.showMessageDialog(null, "Cannot create box of current configuration", "Error: Box Unavailable", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_addToOrderButtonMouseClicked

    private void widthInputStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_widthInputStateChanged
    {//GEN-HEADEREND:event_widthInputStateChanged
        // TODO add your handling code here:
        try{
            width = (double) widthInput.getValue();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please Input a number between 0.1 and 5", "Error: Incorrect Input", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_widthInputStateChanged

    private void heightInputStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_heightInputStateChanged
    {//GEN-HEADEREND:event_heightInputStateChanged
        // TODO add your handling code here:
        try{
        height = (double) heightInput.getValue();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please Input a number between 0.1 and 5", "Error: Incorrect Input", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_heightInputStateChanged

    private void depthInputStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_depthInputStateChanged
    {//GEN-HEADEREND:event_depthInputStateChanged
        // TODO add your handling code here:
        try{
        depth = (double) depthInput.getValue();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please Input a number between 0.1 and 5", "Error: Incorrect Input", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_depthInputStateChanged

    private void quantityInputStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_quantityInputStateChanged
    {//GEN-HEADEREND:event_quantityInputStateChanged
        // TODO add your handling code here:
        try{
        quantity = (int) quantityInput.getValue();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please Input a number between 1 and 100", "Error: Incorrect Input", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_quantityInputStateChanged

    private void grade1RadioButtonStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_grade1RadioButtonStateChanged
    {//GEN-HEADEREND:event_grade1RadioButtonStateChanged
        // TODO add your handling code here:
        if (grade1RadioButton.isSelected())
        {
            grade = 1;
        }
    }//GEN-LAST:event_grade1RadioButtonStateChanged

    private void grade2RadioButtonStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_grade2RadioButtonStateChanged
    {//GEN-HEADEREND:event_grade2RadioButtonStateChanged
        // TODO add your handling code here:
        if (grade2RadioButton.isSelected())
        {
            grade = 2;
        }
    }//GEN-LAST:event_grade2RadioButtonStateChanged

    private void grade3RadioButtonStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_grade3RadioButtonStateChanged
    {//GEN-HEADEREND:event_grade3RadioButtonStateChanged
        // TODO add your handling code here:
        if (grade3RadioButton.isSelected())
        {
            grade = 3;
        }
    }//GEN-LAST:event_grade3RadioButtonStateChanged

    private void grade4RadioButtonStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_grade4RadioButtonStateChanged
    {//GEN-HEADEREND:event_grade4RadioButtonStateChanged
        // TODO add your handling code here:
        if (grade4RadioButton.isSelected())
        {
            grade = 4;
        }
    }//GEN-LAST:event_grade4RadioButtonStateChanged

    private void grade5RadioButtonStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_grade5RadioButtonStateChanged
    {//GEN-HEADEREND:event_grade5RadioButtonStateChanged
        // TODO add your handling code here:
        if (grade5RadioButton.isSelected())
        {
            grade = 5;
        }
    }//GEN-LAST:event_grade5RadioButtonStateChanged

    private void colourNoneRadioButtonStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_colourNoneRadioButtonStateChanged
    {//GEN-HEADEREND:event_colourNoneRadioButtonStateChanged
        // TODO add your handling code here:
        if (colourNoneRadioButton.isSelected())
        {
            colour = 0;
        }
    }//GEN-LAST:event_colourNoneRadioButtonStateChanged

    private void colour1RadioButtonStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_colour1RadioButtonStateChanged
    {//GEN-HEADEREND:event_colour1RadioButtonStateChanged
        // TODO add your handling code here:
        if (colour1RadioButton.isSelected())
        {
            colour = 1;
        }
    }//GEN-LAST:event_colour1RadioButtonStateChanged

    private void colour2RadioButtonStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_colour2RadioButtonStateChanged
    {//GEN-HEADEREND:event_colour2RadioButtonStateChanged
        // TODO add your handling code here:
        if (colour2RadioButton.isSelected())
        {
            colour = 2;
        }
    }//GEN-LAST:event_colour2RadioButtonStateChanged

    private void reinforcedBottomInputStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_reinforcedBottomInputStateChanged
    {//GEN-HEADEREND:event_reinforcedBottomInputStateChanged
        // TODO add your handling code here:
        reinforcedBottom = reinforcedBottomInput.isSelected();
    }//GEN-LAST:event_reinforcedBottomInputStateChanged

    private void reinforcedCornerInputStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_reinforcedCornerInputStateChanged
    {//GEN-HEADEREND:event_reinforcedCornerInputStateChanged
        // TODO add your handling code here:
        reinforcedCorner = reinforcedCornerInput.isSelected();
    }//GEN-LAST:event_reinforcedCornerInputStateChanged

    private void sealableTopInputStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_sealableTopInputStateChanged
    {//GEN-HEADEREND:event_sealableTopInputStateChanged
        // TODO add your handling code here:
        sealableTop = sealableTopInput.isSelected();
    }//GEN-LAST:event_sealableTopInputStateChanged

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_clearButtonMouseClicked
    {//GEN-HEADEREND:event_clearButtonMouseClicked
        // TODO add your handling code here:
        order = new Order();
        grade = 1;
        grade1RadioButton.setSelected(true);
        colour = 0;
        colourNoneRadioButton.setSelected(true);
        quantity = 1;
        quantityInput.setValue(1);
        depth = 0.1;
        depthInput.setValue(0.1);
        height = 0.1;
        heightInput.setValue(0.1);
        width = 0.1;
        widthInput.setValue(0.1);
        sealableTop = false;
        sealableTopInput.setSelected(false);
        reinforcedCorner = false;
        reinforcedCornerInput.setSelected(false);
        reinforcedBottom = false;
        reinforcedBottomInput.setSelected(false);
        text = " ";
        output.setText(text);
        price.setText("Total Price: £0");

    }//GEN-LAST:event_clearButtonMouseClicked

    public static Order order;
    static int grade, colour, quantity;
    static double depth, height, width;
    static boolean sealableTop, reinforcedCorner, reinforcedBottom;
    public static String text = "";

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GUI().setVisible(true);
                order = new Order();
                grade = 1;
                colour = 0;
                quantity = 1;
                depth = 0.1;
                height = 0.1;
                width = 0.1;
                sealableTop = false;
                reinforcedCorner = false;
                reinforcedBottom = false;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToOrderButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JRadioButton colour1RadioButton;
    private javax.swing.JRadioButton colour2RadioButton;
    private javax.swing.ButtonGroup colourButtonGroup;
    private javax.swing.JRadioButton colourNoneRadioButton;
    private javax.swing.JPanel colourPanel;
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JSpinner depthInput;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JRadioButton grade1RadioButton;
    private javax.swing.JRadioButton grade2RadioButton;
    private javax.swing.JRadioButton grade3RadioButton;
    private javax.swing.JRadioButton grade4RadioButton;
    private javax.swing.JRadioButton grade5RadioButton;
    private javax.swing.ButtonGroup gradeButtonGroup;
    private javax.swing.JPanel gradePanel;
    private javax.swing.JSpinner heightInput;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel otherPanel;
    private javax.swing.JTextArea output;
    private javax.swing.JLabel price;
    private javax.swing.JSpinner quantityInput;
    private javax.swing.JToggleButton reinforcedBottomInput;
    private javax.swing.JToggleButton reinforcedCornerInput;
    private javax.swing.JToggleButton sealableTopInput;
    private javax.swing.JPanel sizePanel;
    private javax.swing.JSpinner widthInput;
    // End of variables declaration//GEN-END:variables
}
